name: test-github-dispatch-provider
on:
  repository_dispatch:
  workflow_dispatch:
jobs:
  run-tests-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: echo "running tests.."